In [2]:
import numpy as np
tensor_id = np.array([1.3,1,4,23.99])
print(tensor_id)

[ 1.3   1.    4.   23.99]


In [3]:
print(tensor_id[0])
print(tensor_id[2])

1.3
4.0


In [4]:
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
print(tensor_2d[3][2])

14
