In [1]:
import tensorflow as tf
import numpy as np

matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

In [2]:
print(matrix1)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [3]:
print(matrix2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
matrix1_tf = tf.constant(matrix1)
matrix2_tf = tf.constant(matrix2)

In [6]:
matrix_product = tf.matmul(matrix1_tf, matrix2_tf)
print(matrix_product)

Tensor("MatMul_1:0", shape=(3, 3), dtype=int32)


In [7]:
matrix_sum = tf.add(matrix1_tf, matrix2_tf)
print(matrix_sum)

Tensor("Add:0", shape=(3, 3), dtype=int32)


In [8]:
matrix3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print(matrix3)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [9]:
matrix_det = tf.matrix_determinant(matrix3)
print(matrix_det)

Tensor("MatrixDeterminant:0", shape=(), dtype=float32)


In [10]:
with tf.Session() as sess:
    result1 = sess.run(matrix_product)
    result2 = sess.run(matrix_sum)
    result3 = sess.run(matrix_det)

In [11]:
print(result1)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [12]:
print(result2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [13]:
print(result3)

55.999992
